### ISSUE TITLE
Ubuntu error

### ISSUE THREAD

**Issue by roi35** [Noname400/HtM-Lite#2]
приветствую\
что б скомпилить базу бтц адресов для убунту не хватает файла ice_secp256k1.so
старый не подходит выдает ошибку
еще спросить хочу. какая разница между лайт версией и про?

**Comment by roi35** [comment]
python3 -B PulsarLite.py -b BTC -dbbtc 99.bf -th 3 -sl 5
File ice_secp256k1.so not found
Traceback (most recent call last):
  File "/home/it/Загрузки/HtM-Lite-main (1)/PulsarLite.py", line 8, in <module>
    from funcP import *
  File "/home/it/Загрузки/HtM-Lite-main (1)/funcP.py", line 7, in <module>
    from consts import *
  File "/home/it/Загрузки/HtM-Lite-main (1)/consts.py", line 10, in <module>
    from secp256k1_lib import privatekey_to_ETH_address, privatekey_to_h160, hash_to_address
  File "/home/it/Загрузки/HtM-Lite-main (1)/secp256k1_lib.py", line 92, in <module>
    ice.scalar_multiplication.argtypes = [ctypes.c_char_p, ctypes.c_char_p]   # pvk,ret
NameError: name 'ice' is not defined

**Comment by Noname400** [comment]
библиотеку добавил обновитесь
лайт это базовый функционал, сейчас будет доведет до версии stable и развитие будет остановлено.
в фуле телеграмм, онлайн баланс, режимы поиска, битности, словари, языки, алгоритмы генерации. в будущем свой сервер для чека онлайн

**Comment by roi35** [comment]
в последней версии выдает ошибку
Traceback (most recent call last):
  File "/usr/lib/python3.10/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.10/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/it/Загрузки/HtM-Lite-main/PulsarLite.py", line 36, in run
    inf.bf_btc = load_BF(inf.db_btc)
  File "/usr/lib/python3.10/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/it/Загрузки/HtM-Lite-main/PulsarLite.py", line 36, in run
    inf.bf_btc = load_BF(inf.db_btc)
  File "/usr/lib/python3.10/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/it/Загрузки/HtM-Lite-main/funcP.py", line 31, in load_BF
    time.sleep(inf.delay*n_int)
  File "/home/it/Загрузки/HtM-Lite-main/PulsarLite.py", line 36, in run
    inf.bf_btc = load_BF(inf.db_btc)
KeyboardInterrupt
  File "/home/it/Загрузки/HtM-Lite-main/funcP.py", line 31, in load_BF
    time.sleep(inf.delay*n_int)
KeyboardInterrupt
  File "/home/it/Загрузки/HtM-Lite-main/PulsarLite.py", line 36, in run
    inf.bf_btc = load_BF(inf.db_btc)
  File "/home/it/Загрузки/HtM-Lite-main/PulsarLite.py", line 36, in run
    inf.bf_btc = load_BF(inf.db_btc)
  File "/usr/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/it/Загрузки/HtM-Lite-main/funcP.py", line 31, in load_BF

**Comment by Noname400** [comment]
строку запуска пожалуйста

**Comment by roi35** [comment]
python3 -B PulsarLite.py -b BTC -dbbtc 77.bf -th 30 -sl 5

**Comment by Noname400** [comment]
что то у вас не правильно скопировалось
перегрузите полностью

**Comment by roi35** [comment]
та вроде все как и в прошлой версии ничего не менял...
заново скопировал и такая же проблема

**Comment by Noname400** [comment]
я сегодня все проверю. может залил случайно промежуточную версию

**Comment by Noname400** [comment]
исправил

**Comment by Noname400** [comment]
![image](https://user-images.githubusercontent.com/74019756/174846050-564307d0-8915-4cae-8039-5f36024eb11d.png)
PLS, Update
